### ISSUE TITLE
[功能需求] 常见中国式审批流/工作流需求

### ISSUE THREAD

**Issue by icesugar** [didi/turbo#19]
希望能支撑以下能力。作为流程引擎底层之外的，业务扩展包。

1、审批人驳回时能选择驳回到指定环节(activity/node)，
    场景：具体业务会驳回到对应环节，后面还会出报表统计岗位差错率
2、定义流程时可定义驳回不重走流程/重走流程
   场景：一非常严格的场景会要求重走流程，一般不重走流程，毕竟不能麻烦领导审批2次。所以领导前是重走流程，领导后的不重走流程。驳回后再提交或审批会直接到领导这里来
3、审批人驳回时可选择驳回不重走流程/重走流程
  场景：业务太灵活时再流程定义时指定的不准确，审批人自己去考虑，反正他的岗位职责就是审批这些因素
4、定义流程时可定义指定环节(activity/node)同一审批人自动审批
  场景:领导可不虚幻审批两次。一般科室下面的人提交后第一个审批的就是科室经理，但是科室经理本身又是后面某个环节的负责人，那就会触发审批两次，因此第二次需要自动审批。

其他的什么发送模版消息，限定环节(activity/node)的审批人来源之类的简单的好实现，上面那种涉及流程驱动的不熟悉turbo不好整。

**Comment by liangchenhui** [comment]
你好，Turbo的定位是兼容部分BPMN2.0的轻量级流程引擎（而非平台），支持可重入交互，主要负责提供稳定而高效的核心能力：流程定义、流程驱动，而节点的具体执行由**接入方实现**，后续可能增加的插件也是类似于流程分析这种基础能力的扩展，不会提供与业务逻辑强相关的扩展能力。
