### ISSUE TITLE
群二维码再更新一个吧，过期了

### ISSUE THREAD

**Issue by sunwuxiang** [didi/turbo#30]
群二维码再更新一个吧，过期了

**Comment by liangchenhui** [comment]
更新了哈~

**Comment by liangchenhui** [comment]
更新在readme了哈~

**Comment by honins** [comment]
@liangchenhui 你好，readme中没看到二维码

**Comment by honins** [comment]
@liangchenhui 你好，readme中没看到群二维码

**Comment by honins** [comment]
@liangchenhui 看了下，readme中有图片地址：`http://img-ys011.didistatic.com/static/didi_opensource/turboWX.png`，但是资源不可用，无法显示

**Comment by hzwjs** [comment]
群满了

**Comment by lthaoshao** [comment]
Close the issues.
Please add WeChat account: logic-flow , and join turbo user group
