### ISSUE TITLE
表结构定义中用了自增id作为主键，但是表之间的关联却没有用自增id做关联？

### ISSUE THREAD

**Issue by wangzhedong** [didi/turbo#4]
我看了下表数据之间的关联关系，设计了自增主键，但是在实际数据中好像并没有用到，也没有进行表之间的关联，而是用了一个uuid进行表数据之间的关联，这样做的话，后续我做多表join查询的时候会有性能问题吧？

**Comment by 11Stefanie** [comment]
您好。1. 我们的业务主键也是区间自增的，正常插入和查询方面性能影响很小； 2. id生成器可以自定义实现；3. join场景需要具体分析，在流程执行过程中turbo没有使用join，也不推荐二次开发时进行join，非流程执行过程对性能要求略低，可以根据自己的场景进行设计。
