### ISSUE TITLE
请问如何支持会签呢

### ISSUE THREAD

**Issue by XiaoQYu** [didi/turbo#58]
确实轻量，精简，没有想明白如何支持会签，或签这种功能

**Comment by lthaoshao** [comment]
Turbo作为轻量级的流程引擎，更关注与流程的执行。对于会签、或签这部分，属于工作流的范畴，需要上层根据需要自主实现。
另外，目前Turbo正在着手对并行网关、包容网关等进行开发，后续会支持更多的场景
