### ISSUE TITLE
engine存在循环依赖的bug，无法正常使用

### ISSUE THREAD

**Issue by ZHAOmingquan** [didi/turbo#63]
![image](https://github.com/didi/turbo/assets/45277561/f53df5b2-1724-4aa9-9f7a-a478ea4ccf0f)

**Comment by lthaoshao** [comment]
springboot 2.6及以上版本中，如果存在循环依赖会拒绝启动
可以添加 spring.main.allow-circular-references=true 来开启支持循环依赖

**Comment by ZHAOmingquan** [comment]
ok，添加配置已解决此问题。此处可考虑优化避免循环依赖，比如使用策略模式而不是工厂模式。
