### ISSUE TITLE
并行网关怎么实现？

### ISSUE THREAD

**Issue by yangchd0814** [didi/turbo#8]
看了源代码，发现getExecuteExecutor方法返回值是单个的，不符合并行网关的需求。是否有考虑到这个场景或者提供个解决思路？

**Comment by 11Stefanie** [comment]
可以考虑通过扩展业务节点来实现，并行网关的本质是在一个节点上同时做多件事，都完成后再提交到下一步（下一个节点）~

**Comment by 11Stefanie** [comment]
可以考虑通过扩展业务节点来实现，并行网关的本质是在一个节点上同时做多件事，都完成后再提交到下一步（下一个节点）~

**Comment by liuhuapiaoyuan** [comment]
怎么自定义节点
